<?php

declare(strict_types=1);

namespace App\Http\Requests\Invoice;

use App\Http\Requests\Concerns\ResolvesBranchInput;
use App\Support\TenantContext;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Create a draft invoice for a customer. Lines are added separately so the
 * draft can be built up before issuing. `invoice_number` is generated by
 * the controller — do not send it.
 */
class StoreInvoiceRequest extends FormRequest
{
    use ResolvesBranchInput;

    public function authorize(): bool
    {
        return true;
    }

    protected function prepareForValidation(): void
    {
        $this->defaultBranchFromContext();

        // Drafts default to being dated today; the real issued_at is stamped
        // by the issue transition anyway.
        if (! $this->filled('issue_date')) {
            $this->merge(['issue_date' => now()->toDateString()]);
        }
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        $tenantId = app(TenantContext::class)->tenantId();

        return [
            'branch_id'   => $this->branchRules($tenantId),
            'customer_id' => [
                'required', 'integer',
                Rule::exists('customers', 'id')
                    ->where(fn ($q) => $q->where('tenant_id', $tenantId)->whereNull('deleted_at')),
            ],
            'issue_date'   => ['required', 'date'],
            'due_date'     => ['nullable', 'date', 'after_or_equal:issue_date'],
            'period_start' => ['nullable', 'date'],
            'period_end'   => ['nullable', 'date', 'after_or_equal:period_start'],
            'currency'     => ['nullable', 'string', 'size:3'],
            'discount_poisha' => ['nullable', 'integer', 'min:0'],
            'notes'        => ['nullable', 'string', 'max:2000'],
            'metadata'     => ['nullable', 'array'],
        ];
    }
}
